_core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('posts/', include('apps.posts.urls')),
    path('panel/', include('apps.panel.urls')),
    path('student/', include('apps.student.urls')),
    path('teacher/', include('apps.teacher.urls')),
    path('accounts/', include('apps.accounts.urls')),


    # =========== api url ===============
    path('api/posts/', include('apps.posts.api.urls')),
    path('api/student/', include('apps.student.api.urls')),
    path('api/teacher/', include('apps.teacher.api.urls')),






    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/teacher/api/urls.py
# urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # Teacher model CRUD API URLs
    path('teachers/list/', api_teacher_list),
    path('teachers/store/', api_teacher_store),
    path('teachers/<int:teacher_id>/show/', api_teacher_show),
    path('teachers/<int:teacher_id>/edit/', api_teacher_edit),
    path('teachers/<int:teacher_id>/update/', api_teacher_update),
    path('teachers/<int:teacher_id>/destroy/', api_teacher_destroy),
]

apps/teacher/urls.py
# urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register/', create_teacher_profile, name='register'),
    path('teacher/<int:teacher_id>/', teacher_detail, name='teacher_detail'),
    path('teacher/profile/', teacher_profile, name='teacher_profile'),
    path('teacher/<int:teacher_id>/edit/', edit_teacher_profile, name='edit_teacher_profile'),


    path('applications/create/<int:job_id>/', create_application, name='create_application'),
    path('applications/<int:application_id>/', application_detail, name='application_detail'),
    path('applications/', application_list, name='application_list'),
    path('applications/update/<int:application_id>/', update_application, name='update_application'),
    path('applications/delete/<int:application_id>/', delete_application, name='delete_application'),


	# CRUD for teacher
    path('panel/teacher/list/', panel_teacher_list, name='panel_teacher_list'),
    path('panel/teacher/create/', panel_teacher_create, name='panel_teacher_create'),
    path('panel/teacher/store/', panel_teacher_store, name='panel_teacher_store'),
    path('panel/teacher/<int:pk>/detail/', panel_teacher_detail, name='panel_teacher_detail'),
    path('panel/teacher/<int:pk>/edit/', panel_teacher_edit, name='panel_teacher_edit'),
    path('panel/teacher/<int:pk>/update/', panel_teacher_update, name='panel_teacher_update'),
    path('panel/teacher/<int:pk>/delete/', panel_teacher_delete, name='panel_teacher_delete'),
]

apps/teacher/models.py
from django.db import models
from apps.student.models import *
from django.contrib.auth import get_user_model

CustomUser = get_user_model()
# Create your models here.
class Teacher(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    is_profile_completed = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)

    # Basic Information
    TEACHER_TYPE_CHOICES = [
        ('individual', 'Individual Teacher'),
        ('tutor', 'Tutor'),
    ]
    teacher_type = models.CharField(max_length=20, choices=TEACHER_TYPE_CHOICES)
    
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    
    location = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    

    # Subjects and Levels
    subjects = models.CharField(max_length=200, help_text="Comma-separated list of subjects")
    from_level = models.IntegerField(help_text="From Grade")
    to_level = models.IntegerField(help_text="To Grade")

    # Teaching Experience
    organization = models.CharField(max_length=100, blank=True)
    designation = models.CharField(max_length=100, blank=True)
    experience_start_date = models.DateField(null=True, blank=True)
    experience_end_date = models.DateField(null=True, blank=True)
    
    ASSOCIATION_CHOICES = [
        ('parttime', 'Part-time'),
        ('fulltime', 'Full-time'),
    ]
    association = models.CharField(max_length=10, choices=ASSOCIATION_CHOICES, blank=True)
    
    job_description = models.TextField(blank=True)
    lesson_plan_details = models.TextField(blank=True)

    # Teaching Details
    FEE_TYPE_CHOICES = [
        ('hourly', 'Hourly'),
        ('monthly', 'Monthly'),
    ]
    fee_type = models.CharField(max_length=10, choices=FEE_TYPE_CHOICES)
    
    max_fee = models.DecimalField(max_digits=10, decimal_places=2)
    min_fee = models.DecimalField(max_digits=10, decimal_places=2)
    fee_details = models.TextField(blank=True)
    tutor_experience_years = models.PositiveIntegerField(default=0)
    industry_experience_years = models.PositiveIntegerField(default=0)
    online_teaching_experience_years = models.PositiveIntegerField(default=0)
    
    willing_to_travel = models.BooleanField(default=False)
    available_for_online_teaching = models.BooleanField(default=False)
    has_digital_pen = models.BooleanField(default=False)
    helps_with_homework = models.BooleanField(default=False)
    is_full_time_teacher = models.BooleanField(default=False)
    
    OPPORTUNITY_CHOICES = [
        ('fulltime', 'Full Time'),
        ('parttime', 'Part Time'),
    ]
    interested_opportunities = models.CharField(max_length=10, choices=OPPORTUNITY_CHOICES)

    # Education
    institute = models.CharField(max_length=100)
    
    DEGREE_TYPE_CHOICES = [
        ('bachelor', 'Bachelor'),
        ('master', 'Master'),
        ('phd', 'PhD'),
    ]
    degree_type = models.CharField(max_length=10, choices=DEGREE_TYPE_CHOICES)
    
    degree_name = models.CharField(max_length=100)
    education_start_date = models.DateField()
    education_end_date = models.DateField(null=True, blank=True)
    
    EDU_ASSOCIATION_CHOICES = [
        ('parttime', 'Part-time'),
        ('fulltime', 'Full-time'),
    ]
    education_association = models.CharField(max_length=10, choices=EDU_ASSOCIATION_CHOICES)
    
    specialities = models.CharField(max_length=200, blank=True)
    score = models.CharField(max_length=50, blank=True, null=True)

    # Profile Description
    profile_description = models.TextField(help_text="Don't share any contact info")

    # Identification
    DOC_TYPE_CHOICES = [
        ('passport', 'Passport'),
        ('drivinglicense', 'Driving License'),
    ]
    document_type = models.CharField(max_length=20, choices=DOC_TYPE_CHOICES)
    document_file = models.FileField(upload_to='teacher_ids/' , blank=True, null=True)



    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.user.email


class Application(models.Model):
    application_status_choices = (
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    )
    job = models.ForeignKey(JobRequirement, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    cover_letter = models.TextField()
    status = models.CharField(max_length=20, choices=application_status_choices)
    applied_at = models.DateTimeField(auto_now_add=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/teacher/forms.py
from django import forms
from .models import *
from apps.helpers import *

class TeacherProfileForm(FormFieldClassMixin,forms.ModelForm):
    class Meta:
        model = Teacher
        exclude = ['user']  # Exclude user as it will be set in the view

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['willing_to_travel'].widget = forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')])
        self.fields['available_for_online_teaching'].widget = forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')])
        self.fields['has_digital_pen'].widget = forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')])
        self.fields['helps_with_homework'].widget = forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')])
        self.fields['is_full_time_teacher'].widget = forms.RadioSelect(choices=[(True, 'Yes'), (False, 'No')])


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        exclude = ['user', 'is_profile_completed', 'is_active', 'is_verified', 'created_at', 'updated_at']


class TeacherPanelForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'

apps/teacher/api/views.py
# views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from ..models import *
from .serializers import *



# Teacher model CRUD API Views
@api_view(['GET'])
def api_teacher_list(request):
    teachers = Teacher.objects.all()
    serializer = TeacherSerializer(teachers, many=True)
    return Response(serializer.data)

@api_view(['POST'])
def api_teacher_store(request):
    serializer = TeacherSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET'])
def api_teacher_show(request, teacher_id):
    try:
        teacher = Teacher.objects.get(id=teacher_id)
        serializer = TeacherSerializer(teacher)
        return Response(serializer.data)
    except Teacher.DoesNotExist:
        return Response({'message': 'Teacher not found'}, status=status.HTTP_404_NOT_FOUND)

@api_view(['GET'])
def api_teacher_edit(request, teacher_id):
    try:
        teacher = Teacher.objects.get(id=teacher_id)
        serializer = TeacherSerializer(teacher)
        return Response(serializer.data)
    except Teacher.DoesNotExist:
        return Response({'message': 'Teacher not found'}, status=status.HTTP_404_NOT_FOUND)

@api_view(['POST'])
def api_teacher_update(request, teacher_id):
    try:
        teacher = Teacher.objects.get(id=teacher_id)
    except Teacher.DoesNotExist:
        return Response({'message': 'Teacher not found'}, status=status.HTTP_404_NOT_FOUND)

    serializer = TeacherSerializer(teacher, data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['POST'])
def api_teacher_destroy(request, teacher_id):
    try:
        teacher = Teacher.objects.get(id=teacher_id)
    except Teacher.DoesNotExist:
        return Response({'message': 'Teacher not found'}, status=status.HTTP_404_NOT_FOUND)

    teacher.delete()
    return Response({'message': 'Teacher deleted successfully'}, status=status.HTTP_204_NO_CONTENT)

apps/teacher/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from django.contrib import messages
from django.views.decorators.http import require_GET, require_POST

# @login_required
def create_teacher_profile(request):
    if request.method == 'POST':
        form = TeacherProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('profile_created')  # Redirect to a success page
    else:
        form = TeacherProfileForm()
    
    return render(request, 'site/page/register_form.html', {'form': form})


def teacher_profile(request):
    teacher = get_object_or_404(Teacher, id=request.user.teacher.id)
    return render(request, 'site/page/teachers/profile.html', {'teacher': teacher})
def teacher_detail(request, teacher_id):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    return render(request, 'site/page/teachers/detail.html', {'teacher': teacher})




def edit_teacher_profile(request, teacher_id):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    
    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect('teacher_profile')  # Redirect to teacher's profile page
    else:
        form = TeacherForm(instance=teacher)
    
    return render(request, 'site/page/teachers/edit_profile.html', {'form': form, 'teacher': teacher})








def has_applied(teacher, job):
    return Application.objects.filter(teacher=teacher, job=job).exists()

@login_required
def create_application(request, job_id):
    if not request.user.is_teacher:
        messages.error(request, "You are not a teacher.")
        return redirect('job_requirement_detail', pk=job_id)
    
    job = get_object_or_404(JobRequirement, id=job_id)
    teacher = request.user.teacher

        # Check if the teacher has already applied
    if has_applied(teacher, job):
        messages.warning(request, "You have already applied for this job.")
        return redirect('application_detail', application_id=Application.objects.get(teacher=teacher, job=job).id)

    if request.method == 'POST':
        cover_letter = request.POST.get('cover_letter')
        application = Application.objects.create(
            job=job,
            teacher=teacher,
            cover_letter=cover_letter,
            status='pending'
        )
        return redirect('application_detail', application_id=application.id)

    return render(request, 'site/page/applications/create.html', {'job': job})

@login_required
def application_detail(request, application_id):
    application = get_object_or_404(Application, id=application_id, teacher=request.user.teacher)
    return render(request, 'site/page/applications/detail.html', {'application': application})

@login_required
def application_list(request):
    applications = Application.objects.filter(teacher=request.user.teacher)
    return render(request, 'site/page/applications/list.html', {'applications': applications})

@login_required
def update_application(request, application_id):
    application = get_object_or_404(Application, id=application_id, teacher=request.user.teacher)

    if request.method == 'POST':
        application.cover_letter = request.POST.get('cover_letter')
        application.save()
        return redirect('application_detail', application_id=application.id)

    return render(request, 'site/page/applications/update.html', {'application': application})

@login_required
def delete_application(request, application_id):
    application = get_object_or_404(Application, id=application_id, teacher=request.user.teacher)

    if request.method == 'POST':
        application.delete()
        return redirect('application_list')

    return render(request, 'site/page/applications/delete.html', {'application': application})




# CRUD for teacher
@require_GET
def panel_teacher_list(request):
    object_list = Teacher.objects.all()
    return render(request, 'panel/pages/teacher/list.html', {'object_list': object_list})

@require_GET
def panel_teacher_create(request):
    form = TeacherPanelForm()
    return render(request, 'panel/pages/teacher/create.html', {'form': form})

@require_POST
def panel_teacher_store(request):
    form = TeacherPanelForm(request.POST, request.FILES)
    if form.is_valid():
        object = form.save()
        return redirect('panel_teacher_detail', pk=object.id)
    return render(request, 'panel/pages/teacher/create.html', {'form': form})

@require_GET
def panel_teacher_detail(request, pk):
    object = get_object_or_404(Teacher, pk=pk)
    return render(request, 'panel/pages/teacher/detail.html', {'object': object})

@require_GET
def panel_teacher_edit(request, pk):
    object = get_object_or_404(Teacher, pk=pk)
    form = TeacherPanelForm(instance=object)
    return render(request, 'panel/pages/teacher/edit.html', {'form': form, 'object': object})

@require_POST
def panel_teacher_update(request, pk):
    object = get_object_or_404(Teacher, pk=pk)
    form = TeacherPanelForm(request.POST, request.FILES, instance=object)
    if form.is_valid():
        form.save()
        return redirect('panel_teacher_detail', pk=object.id)
    return render(request, 'panel/pages/teacher/edit.html', {'form': form, 'object': object})

@require_POST
def panel_teacher_delete(request, pk):
    object = get_object_or_404(Teacher, pk=pk)
    object.delete()
    return redirect('panel_teacher_list')

templates/site/page/teachers/detail.html
{% extends 'site/layouts/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<div class="container section-form p-8">
  <h1 class="text-xl font-bold mb-6">Name: {{ teacher.user.name }}</h1>

  <h2 class="  text-lg font-semibold mt-6 mb-1">Basic Information</h2>
  <p><strong>Type:</strong> {{ teacher.get_teacher_type_display }}</p>
  <p><strong>Gender:</strong> {{ teacher.get_gender_display }}</p>
  <p><strong>Location:</strong> {{ teacher.location }} ({{ teacher.postal_code }})</p>

  <h2 class="  text-lg font-semibold mt-6 mb-1">Contact Information</h2>
  <p><strong>Email:</strong> {{ teacher.user.email }}</p>
  <p><strong>Phone:</strong> {{ teacher.user.phone }}</p>
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Teaching Information</h2>
  <p><strong>Subjects:</strong> {{ teacher.subjects }}</p>
  <p><strong>Grade Levels:</strong> {{ teacher.from_level }} to {{ teacher.to_level }}</p>
  <p><strong>Fee Type:</strong> {{ teacher.get_fee_type_display }}</p>
  <p><strong>Fee Range:</strong> ${{ teacher.min_fee }} - ${{ teacher.max_fee }} {{ teacher.fee_type }}</p>
  {% if teacher.fee_details %}<p><strong>Fee Details:</strong> {{ teacher.fee_details }}</p>{% endif %}
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Experience</h2>
  <p><strong>Organization:</strong> {{ teacher.organization }}</p>
  <p><strong>Designation:</strong> {{ teacher.designation }}</p>
  <p><strong>Duration:</strong> {{ teacher.experience_start_date }} to {% if teacher.experience_end_date %}{{ teacher.experience_end_date }}{% else %}Present{% endif %} ({{ teacher.get_association_display }})</p>
  <p><strong>Job Description:</strong> {{ teacher.job_description }}</p>
  <p><strong>Lesson Plan Details:</strong> {{ teacher.lesson_plan_details }}</p>
  
  <p><strong>Years of Experience:</strong></p>
  <ul>
    <li>Tutoring: {{ teacher.tutor_experience_years }} years</li>
    <li>Industry: {{ teacher.industry_experience_years }} years</li>
    <li>Online Teaching: {{ teacher.online_teaching_experience_years }} years</li>
  </ul>
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Education</h2>
  <p><strong>Institute:</strong> {{ teacher.institute }}</p>
  <p><strong>Degree:</strong> {{ teacher.get_degree_type_display }} in {{ teacher.degree_name }}</p>
  <p><strong>Duration:</strong> {{ teacher.education_start_date }} to {% if teacher.education_end_date %}{{ teacher.education_end_date }}{% else %}Present{% endif %} ({{ teacher.get_education_association_display }})</p>
  <p><strong>Specialities:</strong> {{ teacher.specialities }}</p>
  {% if teacher.score %}<p><strong>Score:</strong> {{ teacher.score }}</p>{% endif %}
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Additional Information</h2>
  <ul>
    <li>Willing to travel: {% if teacher.willing_to_travel %}Yes{% else %}No{% endif %}</li>
    <li>Available for online teaching: {% if teacher.available_for_online_teaching %}Yes{% else %}No{% endif %}</li>
    <li>Has digital pen: {% if teacher.has_digital_pen %}Yes{% else %}No{% endif %}</li>
    <li>Helps with homework: {% if teacher.helps_with_homework %}Yes{% else %}No{% endif %}</li>
    <li>Full-time teacher: {% if teacher.is_full_time_teacher %}Yes{% else %}No{% endif %}</li>
    <li>Interested in: {{ teacher.get_interested_opportunities_display }} opportunities</li>
  </ul>
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Profile Description</h2>
  <p>{{ teacher.profile_description }}</p>
  
  {% if user.is_staff %}
  <h2 class="  text-lg font-semibold mt-6 mb-1">Administration</h2>
  <p><strong>Status:</strong> {% if teacher.is_active %}Active{% else %}Inactive{% endif %}, {% if teacher.is_verified %}Verified{% else %}Not Verified{% endif %}</p>
  <p><strong>Profile Completion:</strong> {% if teacher.is_profile_completed %}Completed{% else %}Incomplete{% endif %}</p>
  <p><strong>ID Document:</strong> {{ teacher.get_document_type_display }} ({{ teacher.document_file }})</p>
  {% endif %}
  

  
</div>

{% endblock %}

templates/site/page/teachers/profile.html
{% extends 'site/layouts/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<div class="container section-form p-8">
  <h1 class="text-xl font-bold mb-6">Name: {{ teacher.user.name }}</h1>

  <h2 class="  text-lg font-semibold mt-6 mb-1">Basic Information</h2>
  <p><strong>Type:</strong> {{ teacher.get_teacher_type_display }}</p>
  <p><strong>Gender:</strong> {{ teacher.get_gender_display }}</p>
  <p><strong>Location:</strong> {{ teacher.location }} ({{ teacher.postal_code }})</p>

  <h2 class="  text-lg font-semibold mt-6 mb-1">Contact Information</h2>
  <p><strong>Email:</strong> {{ teacher.user.email }}</p>
  <p><strong>Phone:</strong> {{ teacher.user.phone }}</p>
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Teaching Information</h2>
  <p><strong>Subjects:</strong> {{ teacher.subjects }}</p>
  <p><strong>Grade Levels:</strong> {{ teacher.from_level }} to {{ teacher.to_level }}</p>
  <p><strong>Fee Type:</strong> {{ teacher.get_fee_type_display }}</p>
  <p><strong>Fee Range:</strong> ${{ teacher.min_fee }} - ${{ teacher.max_fee }} {{ teacher.fee_type }}</p>
  {% if teacher.fee_details %}<p><strong>Fee Details:</strong> {{ teacher.fee_details }}</p>{% endif %}
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Experience</h2>
  <p><strong>Organization:</strong> {{ teacher.organization }}</p>
  <p><strong>Designation:</strong> {{ teacher.designation }}</p>
  <p><strong>Duration:</strong> {{ teacher.experience_start_date }} to {% if teacher.experience_end_date %}{{ teacher.experience_end_date }}{% else %}Present{% endif %} ({{ teacher.get_association_display }})</p>
  <p><strong>Job Description:</strong> {{ teacher.job_description }}</p>
  <p><strong>Lesson Plan Details:</strong> {{ teacher.lesson_plan_details }}</p>
  
  <p><strong>Years of Experience:</strong></p>
  <ul>
    <li>Tutoring: {{ teacher.tutor_experience_years }} years</li>
    <li>Industry: {{ teacher.industry_experience_years }} years</li>
    <li>Online Teaching: {{ teacher.online_teaching_experience_years }} years</li>
  </ul>
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Education</h2>
  <p><strong>Institute:</strong> {{ teacher.institute }}</p>
  <p><strong>Degree:</strong> {{ teacher.get_degree_type_display }} in {{ teacher.degree_name }}</p>
  <p><strong>Duration:</strong> {{ teacher.education_start_date }} to {% if teacher.education_end_date %}{{ teacher.education_end_date }}{% else %}Present{% endif %} ({{ teacher.get_education_association_display }})</p>
  <p><strong>Specialities:</strong> {{ teacher.specialities }}</p>
  {% if teacher.score %}<p><strong>Score:</strong> {{ teacher.score }}</p>{% endif %}
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Additional Information</h2>
  <ul>
    <li>Willing to travel: {% if teacher.willing_to_travel %}Yes{% else %}No{% endif %}</li>
    <li>Available for online teaching: {% if teacher.available_for_online_teaching %}Yes{% else %}No{% endif %}</li>
    <li>Has digital pen: {% if teacher.has_digital_pen %}Yes{% else %}No{% endif %}</li>
    <li>Helps with homework: {% if teacher.helps_with_homework %}Yes{% else %}No{% endif %}</li>
    <li>Full-time teacher: {% if teacher.is_full_time_teacher %}Yes{% else %}No{% endif %}</li>
    <li>Interested in: {{ teacher.get_interested_opportunities_display }} opportunities</li>
  </ul>
  
  <h2 class="  text-lg font-semibold mt-6 mb-1">Profile Description</h2>
  <p>{{ teacher.profile_description }}</p>
  
  {% if user.is_staff %}
  <h2 class="  text-lg font-semibold mt-6 mb-1">Administration</h2>
  <p><strong>Status:</strong> {% if teacher.is_active %}Active{% else %}Inactive{% endif %}, {% if teacher.is_verified %}Verified{% else %}Not Verified{% endif %}</p>
  <p><strong>Profile Completion:</strong> {% if teacher.is_profile_completed %}Completed{% else %}Incomplete{% endif %}</p>
  <p><strong>ID Document:</strong> {{ teacher.get_document_type_display }} ({{ teacher.document_file }})</p>
  {% endif %}

  <a href="{% url 'edit_teacher_profile' teacher.id %}" class="btn btn-primary btn-nm my-4 rounded-none">Edit Profile</a>
  

  
</div>

{% endblock %}